lib/app_web/router.ex
defmodule AppWeb.Router do
  use AppWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", AppWeb do
    pipe_through :browser

    get "/", PageController, :index
    get "/posts", PostController, :index
    get "/posts/:slug", PostController, :show
    get "/projects", ProjectController, :index
    get "/projects/:slug", ProjectController, :show
    get "/about", AboutController, :index
    resources "/contact", EmailController, only: [:index, :create]
  end

  # Other scopes may use custom stacks.
  # scope "/api", AppWeb do
  #   pipe_through :api
  # end
end

lib/app_web/views/layout_view.ex
defmodule AppWeb.LayoutView do
  use AppWeb, :view

  def active_class(conn, path) do
    current_path = Path.join(["/" | conn.path_info])
    if path == current_path do
      "active"
    else
      nil
    end
  end

  def avatar_url() do
    App.Github.Api.avatar_url()
  end
end

lib/app_web/templates/layout/_footer.html.eex
<footer class="bg-white border-t border-gray-400 shadow mt-16">
    <div class="container max-w-6xl mx-auto flex py-8">

        <div class="w-full mx-auto flex flex-wrap md:justify-evenly justify-left">
            <div class="md:w-1/2">
                <div class="px-8">
                    <h3 class="font-bold text-gray-900">About</h3>
                    <p class="py-4 text-gray-600 text-sm">
                        I'm Ben ~ a mechatronics engineer and freelance software developer.
                        Drop me an <a href="<%= Routes.email_path(@conn, :index) %>">e-mail</a> and let me know what you're working on!
                    </p>
                    <p class="py-4 text-gray-600 text-sm">
                        PGP Fingerprint <br>
                        A3B6 2217 43B4 657C 685F  55BF 5D69 CF7F A9C5 E2A6 <br>
                    </p>
                </div>
            </div>

            <div class="w-auto pb-8">
                <div class="px-8">
                    <h3 class="font-bold text-gray-900">Social</h3>
                    <ul class="list-reset items-center text-sm pt-3">
                        <li>
                            <a class="inline-block text-gray-600 no-underline hover:text-gray-900 hover:text-underline py-1"
                                href="https://github.com/BenSchZA">GitHub @BenSchZA</a>
                        </li>
                        <li>
                            <a class="inline-block text-gray-600 no-underline hover:text-gray-900 hover:text-underline py-1"
                                href="https://stackoverflow.com/users/2351499/yodascholtz">StackOverflow
                                @yodascholtz</a>
                        </li>
                        <li>
                            <a class="inline-block text-gray-600 no-underline hover:text-gray-900 hover:text-underline py-1"
                                href="https://www.linkedin.com/in/benjaminscholtz/">LinkedIn @benjaminscholtz</a>
                        </li>
                        <li>
                            <a class="inline-block text-gray-600 no-underline hover:text-gray-900 hover:text-underline py-1"
                                href="https://twitter.com/BenScholtz">Twitter @benscholtz</a>
                        </li>
                        <li>
                            <a class="inline-block text-gray-600 no-underline hover:text-gray-900 hover:text-underline py-1"
                                href="https://medium.com/@benscholtz">Medium @benscholtz</a>
                        </li>
                        <li>
                            <a class="inline-block text-gray-600 no-underline hover:text-gray-900 hover:text-underline py-1"
                                href="https://devpost.com/BenSchZA">DevPost @BenSchZA</a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</footer>

lib/app_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta http-equiv="X-UA-Compatible" content="ie=edge">
	<title>Bits of Ether</title>
	<meta name="author" content="Benjamin Scholtz">
	<meta name="description" content="Freelance engineering and software development">
	<meta name="keywords" content="engineering,software,fintech,automation">
	<link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>" />
	<link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro&display=swap" rel="stylesheet">
	<link href="https://fonts.googleapis.com/css?family=Pacifico&display=swap" rel="stylesheet">
</head>
  
<body class="flex min-h-screen flex-col bg-gray-200 font-sans leading-normal tracking-normal">
	<a href="https://github.com/BenSchZA/phoenix-blog" class="github-corner" aria-label="View source on GitHub"><svg width="80" height="80" viewBox="0 0 250 250" style="fill:#151513; color:#fff; position: absolute; top: 0; border: 0; left: 0; transform: scale(-1, 1);" aria-hidden="true"><path d="M0,0 L115,115 L130,115 L142,142 L250,250 L250,0 Z"></path><path d="M128.3,109.0 C113.8,99.7 119.0,89.6 119.0,89.6 C122.0,82.7 120.5,78.6 120.5,78.6 C119.2,72.0 123.4,76.3 123.4,76.3 C127.3,80.9 125.5,87.3 125.5,87.3 C122.9,97.6 130.6,101.9 134.4,103.2" fill="currentColor" style="transform-origin: 130px 106px;" class="octo-arm"></path><path d="M115.0,115.0 C114.9,115.1 118.7,116.5 119.8,115.4 L133.7,101.6 C136.9,99.2 139.9,98.4 142.2,98.6 C133.8,88.0 127.5,74.4 143.8,58.0 C148.5,53.4 154.0,51.2 159.7,51.0 C160.3,49.4 163.2,43.6 171.4,40.1 C171.4,40.1 176.1,42.5 178.8,56.2 C183.1,58.6 187.2,61.8 190.9,65.4 C194.5,69.0 197.7,73.2 200.1,77.6 C213.8,80.2 216.3,84.9 216.3,84.9 C212.7,93.1 206.9,96.0 205.4,96.6 C205.1,102.4 203.0,107.8 198.3,112.5 C181.9,128.9 168.3,122.5 157.7,114.1 C157.9,116.9 156.7,120.9 152.7,124.9 L141.0,136.5 C139.8,137.7 141.6,141.9 141.8,141.8 Z" fill="currentColor" class="octo-body"></path></svg><style>.github-corner:hover .octo-arm{animation:octocat-wave 560ms ease-in-out}@keyframes octocat-wave{0%,100%{transform:rotate(0)}20%,60%{transform:rotate(-25deg)}40%,80%{transform:rotate(10deg)}}@media (max-width:500px){.github-corner:hover .octo-arm{animation:none}.github-corner .octo-arm{animation:octocat-wave 560ms ease-in-out}}</style></a>

	<nav id="header" class="fixed w-full z-10 top-0">

		<div id="progress" class="h-1 z-20 top-0"
			style="background:linear-gradient(to right, #4dc0b5 var(--scroll), transparent 0);"></div>

		<div class="md:px-16 px-4 w-full md:max-w-4xl mx-auto flex flex-wrap items-center justify-end mt-0 py-3">

			<div class="hidden md:block">
				<div class="avatar inline-block rounded-full bg-gray-300 pr-5 h-10">
					<img class="rounded-full float-left h-full" src="<%= avatar_url()  %>">
					<a class="ml-3 text-gray-900 text-base no-underline hover:no-underline font-extrabold text-xl" href="/#">
						Benjamin Scholtz
					</a>
				</div>
			</div>

			<div class="block md:hidden md:object-right">
				<button id="nav-toggle"
					class="flex items-center px-3 py-2 border rounded text-gray-500 border-gray-600 hover:text-gray-900 hover:border-teal-500 appearance-none focus:outline-none">
					<svg class="fill-current h-3 w-3" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
						<title>Menu</title>
						<path d="M0 3h20v2H0V3zm0 6h20v2H0V9zm0 6h20v2H0v-2z" />
					</svg>
				</button>
			</div>

			<div class="w-full flex-grow md:flex md:items-center md:w-auto hidden md:block mt-2 md:mt-0 bg-gray-100 md:bg-transparent z-20"
				id="nav-content">
				<ul class="list-reset md:flex justify-end flex-1 items-center">
					<li class="">
						  <a class="menu-link <%= active_class(@conn, Routes.page_path(@conn, :index))%>"
							     href="/#">Home</a>
					</li>
					<li class="">
						<a class="menu-link <%= active_class(@conn, Routes.about_path(@conn, :index))%>"
							href="<%= Routes.about_path(@conn, :index) %>">About</a>
					</li>
					<li class="">
						<a class="menu-link <%= active_class(@conn, Routes.post_path(@conn, :index))%>"
							href="<%= Routes.post_path(@conn, :index) %>">Blog</a>
					</li>
					<li class="">
						<a class="menu-link <%= active_class(@conn, Routes.project_path(@conn, :index))%>"
							href="<%= Routes.project_path(@conn, :index) %>">Projects</a>
					</li>
					<li class="">
						<a class="menu-link <%= active_class(@conn, Routes.email_path(@conn, :index))%>"
							href="<%= Routes.email_path(@conn, :index) %>">Contact</a>
					</li>
				</ul>
			</div>
		</div>
	</nav>

	<div class="flex-1 container w-full md:max-w-3xl mx-auto pt-20">
		<div class="w-full px-4 md:px-6 text-xl text-gray-800 leading-normal">
			<script type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
			<main role="main" class="container">
				<p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
				<p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
				<%= render @view_module, @view_template, assigns %>
			</main>
		</div>
	</div>

	<%= render "_footer.html", conn: @conn %>

	<script>
		/* Progress bar */
		//Source: https://alligator.io/js/progress-bar-javascript-css-variables/
		var h = document.documentElement,
			b = document.body,
			st = 'scrollTop',
			sh = 'scrollHeight',
			progress = document.querySelector('#progress'),
			scroll;
		var scrollpos = window.scrollY;
		var header = document.getElementById("header");
		var navcontent = document.getElementById("nav-content");

		document.addEventListener('scroll', function () {
			/*Refresh scroll % width*/
			scroll = (h[st] || b[st]) / ((h[sh] || b[sh]) - h.clientHeight) * 100;
			progress.style.setProperty('--scroll', scroll + '%');

			/*Apply classes for slide in bar*/
			scrollpos = window.scrollY;

			if (scrollpos > 10) {
				header.classList.add("bg-white");
				header.classList.add("shadow");
				navcontent.classList.remove("bg-gray-100");
				navcontent.classList.add("bg-white");
			}
			else {
				header.classList.remove("bg-white");
				header.classList.remove("shadow");
				navcontent.classList.remove("bg-white");
				navcontent.classList.add("bg-gray-100");
			}

		});


		//Javascript to toggle the menu

		// Detect all clicks on the document
		document.addEventListener("click", function(event) {
			if (event.target.closest("#nav-toggle")) {
				console.log("b")
				//Javascript to toggle the menu
				document.getElementById("nav-content").classList.toggle("hidden");
			} else if (event.target.closest(".nav-content")) {
				console.log("A")
				return;
			} else {
				console.log("c")
				// If user clicks outside the element, hide it!
				document.getElementById("nav-content").classList.add("hidden");
			}
		});
	</script>

	<!-- Calendly badge widget begin -->
	<%# <link href="https://assets.calendly.com/assets/external/widget.css" rel="stylesheet"> %>
	<%# <script src="https://assets.calendly.com/assets/external/widget.js" type="text/javascript"></script> %>
	<%# <script type="text/javascript">Calendly.initBadgeWidget({ url: 'https://calendly.com/bensch-dev/60min?hide_event_type_details=1', text: 'Schedule time with me', color: '#4dc0b5', textColor: '#ffffff', branding: true });</script> %>
	<!-- Calendly badge widget end -->

</body>

</html>